### ISSUE TITLE
Don't export anything

### ISSUE THREAD

**Issue by ararslan** [JuliaMath/AbstractFFTs.jl#3]
Since the package isn't intended to be used directly, I think we should avoid exporting anything from this package to avoid naming conflicts. Packages which extend the functionality provided by AbstractFFTs will still need to `import` anyway, and they can `export` the AbstractFFTs functions they've overloaded.

Does this seem reasonable? cc @stevengj

**Comment by stevengj** [comment]
My impression is the opposite.  If a package just wants `fft(x)` and similar, I can imagine it doing something like:
```jl
using AbstractFFTs
import SomeFFTImplementation
```
where `SomeFFTImplementation` is e.g. determined at build time (maybe FFTW, maybe MKL, maybe FFTPACK, etcetera).  They wouldn't want `using SomeFFTImplementation` because they don't want the symbols specific to that implementation (FFTW.PATIENT or whatever).

**Comment by ararslan** [comment]
Ah, I see what you mean. Never mind then.

**Comment by musm** [comment]
I think it should be be possible to avoid having users to do
```
using AbstractFFTs
import SomeFFTImplementation
``` 
and simply just
```
using SomeFFTImplementation
```
where `SomeFFTImplementation` has implemented the `AbstractFFTs` by requiring it

**Comment by stevengj** [comment]
@musm, yes, that should be possible too.  But if you want to support multiple FFT implementations, or you don't want other symbols that SomeFFTImplementation has exported, you could do it my way instead.
