### ISSUE TITLE
Add support of Frequencies on non-0 Nyquist Band to fftfreq?

### ISSUE THREAD

**Issue by N5N3** [JuliaMath/AbstractFFTs.jl#41]
Now `fftfreq` only return the frequency axis on the 0th Nyquist Band by default.
Maybe we could add a argument, i.e. fc, to determine where the axis is, like:
```julia
fftfreq(10,1,0.3)
10-element Frequencies{Float64}:
  0.0
  0.1
  0.2
  0.3
  0.4
  0.5
  0.6
  0.7
 -0.2
 -0.1
```

**Comment by stevengj** [comment]
Once you have signals whose bandwidth lies in some other range, I suspect we'll have to leave it up to the user to make their axis what they want — after all, the bandwidth does not even need to be contiguous.

**Comment by N5N3** [comment]
As fftfreq is used for fft outputs, if the signal was sampled under Nyquist Law, the appropriate frequency axis should be [fc-0.5fs,fc+0.5fs). 

Anyway, we could use DUC/DDC to make fc equals to 0, and the option seems non-essential. But I thought it might be more “elegant”？

**Comment by stevengj** [comment]
(There is also a multi-band version of Nyquist's law.  Basically it just boils down to the bandwidth(s) not overlapping due to aliasing.)

I think that in the vast majority of cases where FFTs are used for sampled signals, the bandwidth has already been shifted to center it on zero.   The `fftfreq` function has been around for decades (in Matlab, Numpy, …) and in all this time it doesn't seem like there has been much of a demand for arbitrary frequency center?

**Comment by N5N3** [comment]
In fact, there no official fftfreq in matlab, only a fileexchange inspired by numpy.

I add this issue because I need a struct like Frequencies to contraint a function's input, but Frequencies only support fc = 0. 

Maybe i should define it myself.
